### ISSUE TITLE
Design the authenticate prompt

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#106]
## Description

Design the authentication prompt that is presented to the user when a app wants to authenticate.

## Acceptance Criteria

- [x] Must show the app info
- [x] Must prompt the user to accept or reject the credentials the app wants to receive
- [x] Must contain the ability to unlock IDM so that the user may select an identity
- [x] Must contain the ability to choose which credentials the user will disclose

**Comment by andreforsousa** [comment]
Hello, here's the current status for this.
It would be great if we have te `prompt` on the wallet side, this would avoid displaying the initial screen (Nomios is locked) without the CTAs and the identity selector.

I've tried to reuse as much as possible the components and structure of the modal-flow so that we can speed up the entire implementation for this.

![authenticate-prompt_01-locked](https://user-images.githubusercontent.com/39052705/56573152-5ff83280-65b8-11e9-87a2-845d24036f00.jpg)
![authenticate-prompt_02](https://user-images.githubusercontent.com/39052705/56573150-5ff83280-65b8-11e9-90fd-e37d713b529e.jpg)
![authenticate-prompt_03](https://user-images.githubusercontent.com/39052705/56573149-5ff83280-65b8-11e9-89e3-4e1a8ee03f94.jpg)
![authenticate-prompt_04](https://user-images.githubusercontent.com/39052705/56573147-5ff83280-65b8-11e9-8536-86431fc8d9e0.jpg)
![authenticate-prompt_05](https://user-images.githubusercontent.com/39052705/56573148-5ff83280-65b8-11e9-8b96-fbf2cc2ab24a.jpg)
![authenticate-prompt_06](https://user-images.githubusercontent.com/39052705/56573146-5f5f9c00-65b8-11e9-960b-074ca098d2f8.jpg)

**Comment by andreforsousa** [comment]
Simplified version with the browser window pop-up:
![nomios-authenticate-prompt_01](https://user-images.githubusercontent.com/39052705/59676562-be5c1e80-91bf-11e9-915a-d8b607c69f84.jpg)
![nomios-authenticate-prompt_02](https://user-images.githubusercontent.com/39052705/59676565-c0be7880-91bf-11e9-8109-c61edb70d0d1.jpg)
![nomios-authenticate-prompt_03](https://user-images.githubusercontent.com/39052705/59676568-c2883c00-91bf-11e9-9b23-f0262787fd86.jpg)
![nomios-authenticate-prompt_04](https://user-images.githubusercontent.com/39052705/59676574-c4ea9600-91bf-11e9-83b1-d361c3822530.jpg)
![nomios-authenticate-prompt_05](https://user-images.githubusercontent.com/39052705/59676580-c74cf000-91bf-11e9-97cd-cc987ad7f6ed.jpg)
![nomios-authenticate-prompt_06](https://user-images.githubusercontent.com/39052705/59676584-c916b380-91bf-11e9-9eda-b6f4fd0b4f79.jpg)
![nomios-authenticate-prompt_07](https://user-images.githubusercontent.com/39052705/59676590-cb790d80-91bf-11e9-8d34-06fe823ad47c.jpg)






Specs here:
https://drive.google.com/open?id=1rexaXUjfE0kWP0b0IBEhAgVN2-QPLKYi
