### ISSUE TITLE
Design the sign prompt

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#107]
## Description

Design the sign prompt that is presented to the user when a app needs something to be signed.

## Acceptance Criteria

- [x] Must show the app info
- [x] Must contain the ability to unlock IDM before actually showing which identity is associated with the session
- [x] Must prompt the user to accept or reject the signing
- [x] Must show the data being signed
- [x] Should optionally show a preview of what is being signed

**Comment by andreforsousa** [comment]
Hello team,
here's the proposal for this, where we've tried to reuse the layout and components applied to the `authenticate-prompt` since it has the same criteria applied to the back end side, if the app is "locked" we need to hide certain information.

The code snippet is presented using only colors from the style-guide, we need to ensure that we can stylise the syntax.

![sign-prompt_01-locked](https://user-images.githubusercontent.com/39052705/57792196-5769c680-7736-11e9-9177-ae9c74374ae1.jpg)
![idm-lock-screen_01](https://user-images.githubusercontent.com/39052705/57792203-59cc2080-7736-11e9-8cfb-f01734521240.jpg)
![sign-prompt_02](https://user-images.githubusercontent.com/39052705/57792209-5cc71100-7736-11e9-9135-50c5b2fc3d47.jpg)
![sign-prompt_03](https://user-images.githubusercontent.com/39052705/57792214-5f296b00-7736-11e9-894f-cdf68d74c7d6.jpg)

**Comment by andreforsousa** [comment]
Simplified version with the browser window pop-up:
![nomios-sign-prompt_01](https://user-images.githubusercontent.com/39052705/59676639-e51a5500-91bf-11e9-9fd1-2c6581432af0.jpg)
![nomios-sign-prompt_02](https://user-images.githubusercontent.com/39052705/59676642-e77caf00-91bf-11e9-8607-cc58f81e3b67.jpg)
![nomios-sign-prompt_03](https://user-images.githubusercontent.com/39052705/59676647-e9df0900-91bf-11e9-96a3-a6e6f0cac665.jpg)
![nomios-sign-prompt_04](https://user-images.githubusercontent.com/39052705/59676659-ee0b2680-91bf-11e9-80c2-922ca9c0e600.jpg)

Specs here:
https://drive.google.com/open?id=18g_VLnVWpi0wQKlXbwlMWeHHPqqB-fT1&authuser=andre.sousa@moxy.studio&usp=drive_fs
