### ISSUE TITLE
Design Nomios symbol and logotype

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#18]
## Description

Design the IDM symbol with logotypes/logomarks and the brand concept

## Acceptance Criteria

- [x] Have a distinctive logo and brand that embeds the keypoints listed in #17

**Comment by satazor** [comment]
I've moved this card to blocked because:

1) We have found a similar logos in other projects
2) We should brainstorm this in #19

**Comment by satazor** [comment]
This issue is now unblocked as we have a name.

**Comment by andreforsousa** [comment]
Hello all!

Related with #17 here's the current proposal with the new concept for the "Nomios" brand, some  of the key-points were kept and included a few new ones since the Naming itself needs an implicit personality, I'm proposing an updated list as well:
- Identity;
- Classical;
- Formal;
- Trustworthy;
- Safe / Secure;
- Distinct;
- "Nomios" means shepherd
- "Nomios" as a mythological character was human in shape, but with horns of goats.

The idea for this was use the "helm" as main point for something protected / safe, include a human figure with a distinct look and using the hint of those horns blended with the helm. The multiplicity of the lines from the beard and shadow on the face are meant to connect with the overall look applied to the app.

I'm attaching some of the possible variants of the brand and also the grid/structure used for its creation, paddings and scale relations between the multiple elements: symbol, typography, vertical and horizontal proportions. If needed these could be tweaked afterwards since we may need to include the app tagline as well.

<img width="1365" alt="Screenshot 2019-03-20 at 15 34 16" src="https://user-images.githubusercontent.com/39052705/54697544-a83db400-4b25-11e9-9de0-eaba047a84dc.png">



@satazor @PedroMiguelSS @dominguesgm
