### ISSUE TITLE
Buy typography font 

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#68]
## Description 

Analyze the best licenses to buy a typographic font.

## Acceptance Criteria

- [x] Ensure that we choose the right license type for our use-case
- [x] Have the font bought
- [x] Include the font in the UIKit repo and update license to state that the font is not licensed under MIT and must be bought separately
- [x] Include the font in the public google drive but restrict its access to certain people
- [x] Create an issue to add google analytics on the project to track the typography usage

**Comment by andreforsousa** [comment]
In order to have a distinct look & feel and go beyond the techish apps, we've looked for this web-font to use across the board in all communication and in-app usage. We've tried to use the least weights variations as possible, but for headlines and flags/captions we think that "Display Regular" and "Medium" are the perfect examples to present our intents.

Can we proceed and do the purchase? Here's the cart preview with proper licensing for our use-case.

<img width="1255" alt="gt sectra - cart" src="https://user-images.githubusercontent.com/39052705/54543850-4a2e9680-4996-11e9-9b44-8d4af025bdaf.png">



@daviddias @pgte @satazor @catiatpereira

**Comment by andreforsousa** [comment]
@satazor the README file is completed, we still need to define the permissions within the font folders, you can see it here: https://docs.google.com/document/d/1TsL-6rGWBulpSZk-2tQiTabs6Fn5ZNakWNYf-_NpzT8

@dominguesgm @PedroMiguelSS one of you guys should add the WOFF2 in the repo, that's the only format we should use across the project which may be accessed through GH. Any question let me know, you can find the files on the same README file quoted above.

**Comment by satazor** [comment]
@catiatpereira can you take care of the last acceptance criteria?

**Comment by satazor** [comment]
Issue to add GA: https://github.com/ipfs-shipyard/pm-idm/issues/98

**Comment by satazor** [comment]
PR: https://github.com/ipfs-shipyard/nomios-web-uikit/pull/8
